version: '3.3'
services:
  fitness-server:
    build:
      context: ./server
      dockerfile: dockerfile
    image: michaelmason1998/react-fitness-app/server
    container_name: React-Fitness-App-Server
    command: node server.js
    ports:
      - "8000:8000"
    networks:
      - app-network
  fitness-client:
    build:
      context: ./client
      dockerfile: dockerfile
    image: michaelmason1998/react-fitness-app/client
    container_name: React-Fitness-App-Client
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    external: true